'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

const BADGE = { DRAFT: 'muted', PUSHED: 'ok', FAILED: 'bad' };

export default function Reports() {
  const router = useRouter();
  const [reports, setReports] = useState(null);
  const [detail, setDetail] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    fetch('/api/py/reports')
      .then(async (r) => {
        if (r.status === 401) return router.push('/login');
        const body = await r.json();
        if (!r.ok) throw new Error(body.detail || 'Could not load reports');
        setReports(body.reports);
      })
      .catch((e) => setError(e.message));
  }, [router]);

  const open = async (id) => {
    const r = await fetch(`/api/py/reports/${id}`);
    if (r.ok) setDetail(await r.json());
  };

  return (
    <>
      <h1>Compiled Reports</h1>
      {error && <div className="alert error">{error}</div>}
      <div className="card">
        {!reports ? 'Loading…' : reports.length === 0 ? 'No reports have been compiled yet.' : (
          <table>
            <thead><tr><th>ID</th><th>Type</th><th>Period</th><th>Data values</th><th>Generated by</th><th>Generated</th><th>Status</th></tr></thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id} style={{ cursor: 'pointer' }} onClick={() => open(r.id)}>
                  <td>{r.id}</td>
                  <td>{r.type === 'OPD' ? '105:01 OPD' : '108 IPD'}</td>
                  <td>{r.period}</td>
                  <td>{r.value_count}</td>
                  <td>{r.generated_by}</td>
                  <td>{new Date(r.generated_at).toLocaleString('en-GB')}</td>
                  <td><span className={`badge ${BADGE[r.push_status] || 'muted'}`}>{r.push_status}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
      {detail && (
        <div className="card">
          <h2>Report {detail.id} — {detail.type} · {detail.period}</h2>
          {detail.push_response && (
            <div className="alert info">DHIS2 response: {detail.push_response.status} — imported {detail.push_response.importCount?.imported ?? 0}, updated {detail.push_response.importCount?.updated ?? 0}, ignored {detail.push_response.importCount?.ignored ?? 0}</div>
          )}
          <div style={{ maxHeight: 420, overflow: 'auto', border: '1px solid var(--line)', borderRadius: 8 }}>
            <table>
              <thead><tr><th>Data element</th><th>Disaggregation</th><th style={{ textAlign: 'right' }}>Value</th></tr></thead>
              <tbody>
                {detail.compiled_data.map((v, i) => (
                  <tr key={i}><td>{v.dataElementName}</td><td>{v.categoryOptionComboName}</td><td style={{ textAlign: 'right', fontWeight: 700 }}>{v.value}</td></tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </>
  );
}
